from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from .views import (UserSignUpApiView, LoginApiView, SocialLoginView,
                    LogoutApiView, UserListApiView, UserUpdateApiView,
                    ChangePasswordApiView, CommentListCreateApiView,
                    CommentUpdateDeleteApiView, FavouriteListCreateApiView,
                    FavouriteUpdateDeleteApiView, FlirtListCreateApiView,
                    FlirtUpdateDeleteApiView, FriendListCreateApiView,
                    FriendUpdateDeleteApiView, ImageLikeListCreateApiView,
                    ImageLikeUpdateDeleteApiView, ImageListCreateApiView,
                    ImageUpdateDeleteApiView, MessageListCreateApiView, MessageUpdateDeleteApiView,
                    PermissionListCreateApiView, PermissionUpdateDeleteApiView,
                    ProfileListApiView, ProfileUpdateApiView,  ProfileUpdateView,
                    UserBlockedListCreateApiView,   UserBlockedUpdateDeleteApiView,
                    UserLikeListCreateApiView, UserLikeUpdateDeleteApiView,
                    UserValidateApiView,  UserViewedListCreateApiView,
                    UserViewedUpdateDeleteApiView, ResendOtpApiView, SearchListApiView)


urlpatterns = [
    path('web/', include('django.contrib.auth.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('social-auth/', include('rest_framework_social_oauth2.urls')),
    path('obtain-auth-token/', obtain_auth_token, name="obtain-token"),
    path('signup/', UserSignUpApiView.as_view(), name='user'),
    path('user-validate/', UserValidateApiView.as_view(), name='user-validate'),
    path('reset-otp/', ResendOtpApiView.as_view(), name='resent-otp'),
    path('login/', LoginApiView.as_view(), name='login'),
    path('social-login/', SocialLoginView.as_view(), name='social-login'),
    path('chpasswd/', ChangePasswordApiView.as_view(), name='change-password'),
    path('logout/', LogoutApiView.as_view(), name='logout'),
    path('user/', UserListApiView.as_view(), name='user'),
    path('user/<int:pk>/', UserUpdateApiView.as_view(), name='user-detail'),

    path('profile/', ProfileListApiView.as_view(), name='profile'),
    path('profile-search/', SearchListApiView.as_view(), name='profile-search'),
    path('profile/<int:pk>/', ProfileUpdateApiView.as_view(), name='profile-detail'),
    path('profile/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile-detail'),
    path('image/', ImageListCreateApiView.as_view(), name='image'),
    path('image/<int:pk>/', ImageUpdateDeleteApiView.as_view(), name='image-detail'),
    path('favourite/', FavouriteListCreateApiView.as_view(), name='favourite'),
    path('favourite/<int:pk>/', FavouriteUpdateDeleteApiView.as_view(), name='favourite-detail'),
    path('userlike/', UserLikeListCreateApiView.as_view(), name='userlike'),
    path('userlike/<int:pk>/', UserLikeUpdateDeleteApiView.as_view(), name='userlike-detail'),
    path('userviewed/', UserViewedListCreateApiView.as_view(), name='userlike'),
    path('userviewed/<int:pk>/', UserViewedUpdateDeleteApiView.as_view(), name='userlike-detail'),
    path('imagelike/', ImageLikeListCreateApiView.as_view(), name='imagelike'),
    path('imagelike/<int:pk>/', ImageLikeUpdateDeleteApiView.as_view(), name='imagelike-detail'),
    path('imagecomment/', CommentListCreateApiView.as_view(), name='comment'),
    path('imagecomment/<int:pk>/', CommentUpdateDeleteApiView.as_view(), name='comment-detail'),
    path('userflirt/', FlirtListCreateApiView.as_view(), name='flirt'),
    path('userflirt/<int:pk>/', FlirtUpdateDeleteApiView.as_view(), name='flirt-detail'),
    path('usermsg/', MessageListCreateApiView.as_view(), name='message'),
    path('usermsg/<int:pk>/', MessageUpdateDeleteApiView.as_view(), name='message-detail'),
    path('friend/', FriendListCreateApiView.as_view(), name='friend'),
    path('friend/<int:pk>/', FriendUpdateDeleteApiView.as_view(), name='friend-detail'),
    path('userblocked/', UserBlockedListCreateApiView.as_view(), name='friend'),
    path('userblocked/<int:pk>/', UserBlockedUpdateDeleteApiView.as_view(), name='friend-detail'),
    path('permission/', PermissionListCreateApiView.as_view(), name='permission'),
    path('permission/<int:pk>/', PermissionUpdateDeleteApiView.as_view(), name='permission-detail'),
]
