# Generated by Django 2.2 on 2020-02-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(max_length=100)),
                ('email_of_customer', models.EmailField(max_length=254)),
                ('phone_of_customer', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.SmallIntegerField(validators=[services.models.validate_month])),
                ('year', models.SmallIntegerField(validators=[services.models.validate_year])),
                ('no_of_days', models.SmallIntegerField(validators=[services.models.validate_no_of_days])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('detail', models.CharField(default='Details will coming soon...', max_length=500)),
                ('created_date', models.DateField(auto_now=True)),
                ('reference_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='...', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode_of_payment', models.CharField(choices=[('NET', 'Net Banking'), ('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card'), ('OTHER', 'Other Payment')], max_length=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('premium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_transaction', to='services.Premium')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_upto', models.DateTimeField()),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='services.Transaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('msg', models.CharField(max_length=250)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_noti', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_noti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.upload_image)),
                ('created_date', models.DateField(auto_now=True)),
                ('from_date_to_display', models.DateField(null=True)),
                ('to_date_to_display', models.DateField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_add', to='services.AddCustomer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
