# Generated by Django 2.2 on 2020-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='transaction',
            name='book_id',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
