# Generated by Django 2.2 on 2023-03-10 07:29

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=16, null=True, unique=True)),
                ('email', models.EmailField(max_length=26, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('blocked_date', models.DateField(null=True)),
                ('deleted_date', models.DateField(null=True)),
                ('code', models.CharField(default='000000', max_length=6)),
                ('deleted_by', models.CharField(choices=[('U', 'user'), ('A', 'admin'), ('O', 'None')], default='O', max_length=1, null=True)),
                ('login_by', models.CharField(choices=[('N', 'normal'), ('E', 'email')], default='N', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=accounts.models.upload_image)),
                ('is_profile', models.BooleanField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_they_views', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_my_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_they_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_my_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_they_flirt', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_i_flirt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('city', models.CharField(default='', max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('seeking_for', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('B', 'both')], max_length=1)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=12)),
                ('about', models.CharField(default='', max_length=255)),
                ('hobby', models.CharField(default='', max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('looking_for', models.CharField(default='', max_length=255)),
                ('religion', models.CharField(default='', max_length=255)),
                ('occupation', models.CharField(default='', max_length=255)),
                ('retired', models.CharField(default='', max_length=255)),
                ('marital_status', models.CharField(default='', max_length=255)),
                ('number_of_children', models.CharField(default='', max_length=255)),
                ('living_at_home', models.CharField(default='', max_length=255)),
                ('last_msg_count', models.IntegerField(default=0)),
                ('last_fav_count', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('W', 'Web'), ('M', 'Mobile')], default='W', max_length=1)),
                ('profile_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tracking', models.BooleanField(default=False)),
                ('hide_online_status', models.BooleanField(default=False)),
                ('friendly_only_can_msg', models.BooleanField(default=False)),
                ('only_friend_can_comment', models.BooleanField(default=False)),
                ('friendly_only_can_view_profile', models.BooleanField(default=False)),
                ('premium_members_only_msg', models.BooleanField(default=False)),
                ('premium_members_only_view', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='they_messaged', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_messaged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeimage', to='accounts.Image')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_they_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_my_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='they_requested', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_they_favou', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_my_favou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentimage', to='accounts.Image')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_they_comment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_my_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='they_blocked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_blocked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
